// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObject.Models
{
    public partial class AnimalSpecies
    {
        public AnimalSpecies()
        {
            Animal = new HashSet<Animal>();
            Cage = new HashSet<Cage>();
        }

        [Key]
        [Column("AnimalSpecies_ID")]
        [StringLength(50)]
        public string AnimalSpeciesId { get; set; }
        [Column("AnimalSpecies_Name")]
        [StringLength(50)]
        public string AnimalSpeciesName { get; set; }
        [Column("AnimalSpecies_Decription")]
        public string AnimalSpeciesDecription { get; set; }

        [InverseProperty("AnimalSpecies")]
        public virtual ICollection<Animal> Animal { get; set; }
        [InverseProperty("AnimalSpecies")]
        public virtual ICollection<Cage> Cage { get; set; }
    }
}