// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObject.Models
{
    public partial class Area
    {
        public Area()
        {
            Cage = new HashSet<Cage>();
        }

        [Key]
        [Column("AreaID")]
        [StringLength(50)]
        public string AreaId { get; set; }
        [Column("Area_area")]
        [StringLength(50)]
        public string AreaArea { get; set; }
        [Column("User_ID")]
        [StringLength(50)]
        public string UserId { get; set; }
        [Required]
        [StringLength(50)]
        public string AreaName { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Area")]
        public virtual User User { get; set; }
        [InverseProperty("Area")]
        public virtual ICollection<Cage> Cage { get; set; }
    }
}