// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObject.Models
{
    public partial class Cage
    {
        [Key]
        [StringLength(50)]
        public string CageId { get; set; }
        [Required]
        [Column("AnimalSpecies_ID")]
        [StringLength(50)]
        public string AnimalSpeciesId { get; set; }
        [Required]
        [Column("Area_ID")]
        [StringLength(50)]
        public string AreaId { get; set; }
        [Column("User_ID")]
        [StringLength(50)]
        public string UserId { get; set; }
        [Column("Cage_area")]
        [StringLength(50)]
        public string CageArea { get; set; }

        [ForeignKey("AnimalSpeciesId")]
        [InverseProperty("Cage")]
        public virtual AnimalSpecies AnimalSpecies { get; set; }
        [ForeignKey("AreaId")]
        [InverseProperty("Cage")]
        public virtual Area Area { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("Cage")]
        public virtual User User { get; set; }
    }
}