// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObject.Models
{
    public partial class Food
    {
        public Food()
        {
            ZooTrainerAnimal = new HashSet<ZooTrainerAnimal>();
        }

        [Key]
        [Column("FoodID")]
        [StringLength(50)]
        public string FoodId { get; set; }
        [Required]
        [StringLength(50)]
        public string FoodName { get; set; }
        [Required]
        [StringLength(50)]
        public string Quantity { get; set; }

        [InverseProperty("Food")]
        public virtual ICollection<ZooTrainerAnimal> ZooTrainerAnimal { get; set; }
    }
}