// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObject.Models
{
    public partial class User
    {
        public User()
        {
            Area = new HashSet<Area>();
            Cage = new HashSet<Cage>();
            ZooTrainerAnimal = new HashSet<ZooTrainerAnimal>();
            Constrain = new HashSet<User>();
            UserNavigation = new HashSet<User>();
        }

        [Key]
        [StringLength(50)]
        public string UserId { get; set; }
        [Required]
        [Column("username")]
        [StringLength(50)]
        public string Username { get; set; }
        [Required]
        [Column("pasword")]
        [StringLength(50)]
        public string Pasword { get; set; }
        [Required]
        [Column("fullname")]
        [StringLength(50)]
        public string Fullname { get; set; }
        [Required]
        [Column("phonenumber")]
        [StringLength(50)]
        public string Phonenumber { get; set; }
        [Required]
        [Column("address")]
        [StringLength(50)]
        public string Address { get; set; }
        [Required]
        [Column("role")]
        [StringLength(50)]
        public string Role { get; set; }
        [Column("experience")]
        [StringLength(50)]
        public string Experience { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Area> Area { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Cage> Cage { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<ZooTrainerAnimal> ZooTrainerAnimal { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("UserNavigation")]
        public virtual ICollection<User> Constrain { get; set; }
        [ForeignKey("ConstrainId")]
        [InverseProperty("Constrain")]
        public virtual ICollection<User> UserNavigation { get; set; }
    }
}